### ISSUE TITLE
[WARNING]: 0 modules were converted

### ISSUE THREAD

**Issue by langowskiadam** [magento/code-migration#42]
Hello,
I have problem with tool - probably I can't understand documentation. This my output:

php bin/migrate.php migrateModuleStructure migration\module1 migration\shiptopay2
[2016-04-27 11:27:55][INFO]: Starting module structure converter
[0;33m[2016-04-27 11:27:55][WARNING]: 0 modules were converted[0m
[2016-04-27 11:27:55][INFO]: Ending module structure converter

inside module1 i have structure of module without magento like that migration\module1\app\code\community\Modulename etc

inside module2 I've got nothing.

Please clearify how code-migration tool should work.

Kind regards

**Comment by sshymko** [comment]
Hi.

Does the module contain `config.xml` file?
File `migration\module1\app\code\community\Vendor\Module\etc\config.xml` needs to exist. Otherwise, the tool would not pick up the module.

Thanks

**Comment by langowskiadam** [comment]
Hello,
yes, it exists.

Kind regards

**Comment by sshymko** [comment]
Another reason could be the file permissions. Please double check that all the module files are readable and all directories are traversable. You're running on Windows, don't you? Than permissions should be not an issue.

Could you please provide an archive of the module for me to reproduce and debug the issue.

Thanks

**Comment by sukhmeetsingh111** [comment]
Hi sshymko,
I am facing the same issue, I am trying this with one local module on local windows system, all permission is set to 777, can you please help or suggest any solution.

**Comment by sshymko** [comment]
Hey @sukhmeetsingh111,
The only way to help is for you to provide an archive of the codebase to be migrated.
Could you please upload it somewhere so that I can take a look at it?

**Comment by gordonknoppe** [comment]
The system only migrates "enabled" extensions and it does this by looking for `<src>/app/etc/modules/*.xml`.  Do you have a corresponding app/etc/modules/Vendor_Module.xml in your <src> directory?

**Comment by tinelps** [comment]
Hi there, i try to run `composer install` and it require me username and password, saying `Authentication required (repo.magento.com)`. I tried to provide some usernames and passwords and it says Invalid credential for `https://repo.magento.com/packages.json`, aborting.
May I know what is the username and password that i need to provide?

**Comment by tinelps** [comment]
hi, im facing the same issue. 
@langowskiadam @sukhmeetsingh111 is your problem solved?

@sshymko @gordonknoppe 
i run the line `c:\php55\php.exe migrate.php migrateModuleStructure c:\apache24\htdocs\src c:\apache24\htdocs\dst`

and i get the output `0 module is converted`.

However, everytime i try to run the command, there is a new folder `Magento` created in my `src` folder. Originally, my `src` folder contains `app\code\community\<vendor>\<modulename>\<otherfolders>`.

**Comment by sukhmeetsingh111** [comment]
Hi @sshymko : Sorry for the late reply but problem is not solved, i am attaching module which i am trying to convert from M1 to M2.
[app.zip](https://github.com/magento/code-migration/files/331316/app.zip)

**Comment by tinelps** [comment]
https://github.com/unirgy/convertm1m2

**Comment by DuncanSentrus** [comment]
Hello,

I'm have the same issue here. I'm trying to upgrade Paymill payment module (https://github.com/paymill/paymill-magento) and getting the same error message.

I have set up a "migrate" directory with following subdirectories:

- dst - destination (for converted module)
- src - with paymill payment module source code
- m1 - magento 1.9.3 CE source code + paymill payment module source
- m2 - newest magento 2 CE (2.1.2)
- tool - migration tool

After setting those up, I've navigated to my "tool" directory in CLI (opened as Administrator) and ran `composer install` as said in manual. After that I ran:
```
C:\migrate\tool>php bin/migrate.php migrateModuleStructure C:\migrate\src C:\migrate\dst
```
Which yielded this result:
```
[2016-10-25 16:08:33][INFO]: Starting module structure converter
←[0;33m[2016-10-25 16:08:33][WARNING]: 0 modules were converted←[0m
[2016-10-25 16:08:33][INFO]: Ending module structure converter
```

Since module has been officially tested on 1.7.2 version I tried the same thing with that version, remapping the dependencies as said in manual. Few warnings came up during remapping but result remain the same.

You can check yourself that all configuration files should be there (as far as I know, I'm not a Magento Developer unfortunately). The module works in 1.7.2 and seems to work in 1.9.3 (haven't tested thoroughly yet). Even though using Windows I checked all directories and disabled "read-only" mode in properties and gave all possible permissions to all possible users. Still no luck.

Please let me know if there's anything else I can do, if there's any other reliable tool or if there's any manual (as in tutorial/instructions) on how to perform that kind of migration manually.

Here's my full setup if you need it: https://drive.google.com/open?id=0B7SU4Nt8Ozk7aWNWQkNQclVZa2s

Best regards,
DS

**Comment by CallumBrankin** [comment]
I'm having the same issue. Have any solutions been found?

**Comment by CallumBrankin** [comment]
the module im trying to convert can be found here: https://github.com/Marko-M/Inchoo_SocialConnect

**Comment by gordonknoppe** [comment]
Please re-test with the latest release.

**Comment by CallumBrankin** [comment]
@gordonknoppe Good job! It has seemed to have migrated the files correctly

**Comment by DuncanSentrus** [comment]
Seems to be working now! Thanks!
