### ISSUE TITLE
How to run "install composer"

### ISSUE THREAD

**Issue by tinelps** [magento/code-migration#55]
Hi, i am new to the magento things. The steps mentioned about running the install composer in the root directory of the toolkit.

I have downloaded the toolkit and extract it to my htdocs, and run it to on my localhost to test. 
> http://127.0.0.1:8083/code-migration-develop/
but i couldn't find any install composer to run. 

Can anyone correct me if im doing it wrongly on the first step? And please teach me how to run the install composer so that i can start creating those folders and use the toolkit. Thanks alot.

**Comment by sshymko** [comment]
@tinelps 
Composer is a standalone command-line tool independent of Magento.
Please refer to the official documentation https://getcomposer.org/ on how to install and use it.

**Please be warned!** The code migration toolkit is meant for PHP programmers with reasonable level of expertise in both Magento 1.x and Magento 2. A casual user unfamiliar with the Magento framework and PHP language will be unable to use the tool. I highly recommend you to seek help from a certified Magento developer, rather than trying to do whatever it is you're trying to achieve yourself.

Regards

**Comment by tinelps** [comment]
@sshymko 
i understand a little more on the toolkit after referring to https://www.youtube.com/watch?v=lXJ6rMdQvkk and able to run `composer install ` from my cmd. I am just doing what my senior asked me to do >.<

Thanks for the suggestion.

**Comment by tinelps** [comment]
@sshymko btw, if i am going to seek for help from a certified magento developer, where can i find them? Does it cost payment? Can't u help me?

**Comment by sshymko** [comment]
@tinelps I'm glad you found the video useful :)

You can search for certified Magento engineers in your area via https://www.magentocommerce.com/certification/directory/
